name: ci-test

on:
  push:
    branches:
      - main
      - test
      - rsc-action

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 20

      - run: pnpm install

      - run: pnpm build
